stream_flags:                  .dsb MAX_STREAMS
stream_note_length_lo:         .dsb MAX_STREAMS
stream_note_length_hi:         .dsb MAX_STREAMS
stream_note_length_counter_lo: .dsb MAX_STREAMS
stream_note_length_counter_hi: .dsb MAX_STREAMS
stream_volume_index:           .dsb MAX_STREAMS
stream_volume_offset:          .dsb MAX_STREAMS
stream_arpeggio_index:         .dsb MAX_STREAMS
stream_arpeggio_offset:        .dsb MAX_STREAMS
stream_pitch_index:            .dsb MAX_STREAMS
stream_pitch_offset:           .dsb MAX_STREAMS
stream_duty_index:             .dsb MAX_STREAMS
stream_duty_offset:            .dsb MAX_STREAMS

stream_channel:                .dsb MAX_STREAMS
stream_channel_register_1:     .dsb MAX_STREAMS
stream_channel_register_2:     .dsb MAX_STREAMS
stream_channel_register_3:     .dsb MAX_STREAMS
stream_channel_register_4:     .dsb MAX_STREAMS

stream_read_address_lo:        .dsb MAX_STREAMS
stream_read_address_hi:        .dsb MAX_STREAMS
stream_return_address_lo:      .dsb MAX_STREAMS
stream_return_address_hi:      .dsb MAX_STREAMS

stream_tempo_counter_lo:       .dsb MAX_STREAMS
stream_tempo_counter_hi:       .dsb MAX_STREAMS
stream_tempo_lo:               .dsb MAX_STREAMS
stream_tempo_hi:               .dsb MAX_STREAMS
